export const stories = [
  {
    profileImg: "/polite-chaos/stories/profile-1.png",
    profileName: "Behance",
    title: ["Designing quiet worlds", "where motion tells", "the whole story"],
    linkLabel: "Explore Work",
    linkSrc: "/sample-project",
    storyImg: "/polite-chaos/stories/story-1.jpg",
  },
  {
    profileImg: "/polite-chaos/stories/profile-2.png",
    profileName: "Dribbble",
    title: ["Light, reflection,", "and invisible form", "in digital motion"],
    linkLabel: "Explore Work",
    linkSrc: "/sample-project",
    storyImg: "/polite-chaos/stories/story-2.jpg",
  },
  {
    profileImg: "/polite-chaos/stories/profile-3.png",
    profileName: "Awwwards",
    title: ["A motion identity", "built around silence,", "texture, and time"],
    linkLabel: "Explore Work",
    linkSrc: "/sample-project",
    storyImg: "/polite-chaos/stories/story-3.jpg",
  },
  {
    profileImg: "/polite-chaos/stories/profile-4.png",
    profileName: "Adobe",
    title: ["When design meets", "science fiction,", "everything glows"],
    linkLabel: "Explore Work",
    linkSrc: "/sample-project",
    storyImg: "/polite-chaos/stories/story-4.jpg",
  },
  {
    profileImg: "/polite-chaos/stories/profile-2.png",
    profileName: "Dribbble",
    title: ["Cinematic branding", "for the in-between", "moments of light"],
    linkLabel: "Explore Work",
    linkSrc: "/sample-project",
    storyImg: "/polite-chaos/stories/story-5.jpg",
  },
  {
    profileImg: "/polite-chaos/stories/profile-4.png",
    profileName: "Adobe",
    title: ["Interactive motion", "built to move softly", "and stay longer"],
    linkLabel: "Explore Work",
    linkSrc: "/sample-project",
    storyImg: "/polite-chaos/stories/story-6.jpg",
  },
];
